# Generated by Django 3.1.7 on 2022-02-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
