# Generated by Django 3.1.7 on 2022-02-27 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20220227_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='orderItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.orderitem'),
        ),
    ]
