# Generated by Django 3.1.7 on 2022-02-27 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_item_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='orderItem',
        ),
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
    ]
