# Generated by Django 3.1.7 on 2022-03-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20220302_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productId',
            field=models.IntegerField(default=True),
        ),
    ]
