# Generated by Django 3.1.7 on 2022-04-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20220307_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='output_field',
            field=models.FloatField(default=0),
        ),
    ]
