# Generated by Django 4.0.6 on 2022-07-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_rename_img_product_image_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
