# Generated by Django 4.0.6 on 2022-07-26 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_delete_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='orderitem',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order'),
        ),
    ]
