# Generated by Django 4.1.1 on 2022-10-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_alter_order_transaction_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
