# Generated by Django 4.1.1 on 2022-10-13 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_order_shippingaddress_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
