# Generated by Django 4.1.1 on 2023-03-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_customer_order_customer_shippingaddress_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
