# Generated by Django 4.1.1 on 2023-03-07 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_shippingaddress_email_shippingaddress_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
